### ISSUE TITLE
Property 'msIndexedDB' does not exist on type 'Window'

### ISSUE THREAD

**Issue by jovanialferez** [astronaut1712/ng2-indexeddb#1]
First, thanks for sharing this awesome library. However, i encountered such error.

Lines referred: 
-- node_modules/ng2-indexeddb/indexeddb.service.ts:280:115 
-- node_modules/ng2-indexeddb/indexeddb.service.ts:310:122 

Some details:
OS: OSX 10.11.6
Browser: Chrome Version 53.0.2785.116 (64-bit)

Thanks again!

**Comment by astronaut1712** [comment]
@jovanialferez I fixed on newest version (1.0.2). please update and try again. :)

**Comment by jovanialferez** [comment]
great! thanks! :)

**Comment by yakdaniels** [comment]
For some reason, I'm still seeing the error on line 310: 

let indexedDB = window.indexedDB || (<any>window).mozIndexedDB || (<any>window).webkitIndexedDB || window.msIndexedDB;

I'm using 1.0.2:
    "ng2-indexeddb": "1.0.2",

Thanks.
